import 'package:flutter/material.dart';

const String splashPage = '/';
const String mainPage = '/main_page';
const String clientTabBox = '/client_tab_page';
const String workerTabBox = '/worker_tab_page';
const String workerUpdateProfile = '/update_profile';
const String clientProfileUpdate = '/update_client_profile';
const String homePage = '/home_page';
const String loginPage = '/login_page';
const String clientRegisterPage = '/client_register_page';
const String workerRegisterPage = '/worker_register_page';
const String onBoarding = '/on_boarding';
const String noInternetRoute = '/no_internet_route';
const String optionPage = '/option_route';
const String notificationRoute = '/notification_route';
const String setting = '/settings_page';
const String role = '/role_screen';
const String clientHomeScreen = '/client_home_screen';
const String workerHomeScreen = '/workerHomeScreen';
const String workerInfoScreen = '/worker_info_screen';
const String categorySkills = '/category_skils';
const String createBusynessScreen = '/create_busyness_screen';
myHeight(context) => MediaQuery.of(context).size.height;
myWidth(context) => MediaQuery.of(context).size.width;
